### ISSUE TITLE
Can't run sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Babay88/AndroidCodeSamplesB#1]
Probably because.. it has no valid manifest:

![image](https://user-images.githubusercontent.com/5357526/69478213-b486b900-0df8-11ea-9023-0c40787f7db8.png)

**Comment by Babay88** [comment]
Nope. I't probably because it's library module. It is not intended to be run alone.

Added an activity that uses the library as an example.
https://github.com/Babay88/AndroidCodeSamplesB/blob/master/sharedzipexample/src/main/java/ru/babay/sharedzipexample/MainActivity.java

**Comment by AndroidDeveloperLB** [comment]
Can you please modify it to show how to share a zipped file that contains any number of files within ?

Also, is it possible to even make it zip within zip? For example, suppose I have 3 files: file1,file2,file3, and I want to share them as a zip that contains file1 and also inside this zip a zipped file that contains file2 and file3. Is it possible?
